### ISSUE TITLE
MissingLibraryException: lib/armeabi/libdl.so

### ISSUE THREAD

**Issue by BlueBirdZhangHua** [KeepSafe/ReLinker#19]
First of all,Thank you for share such a great project!! We had this problem for many yeas!
I run the Sample project. After delete the so file it seems that  after parseNeededDependencies it try to load libdl.so. 
```
04-29 16:32:21.888 22887-23167/com.getkeepsafe.relinker.sample E/AndroidRuntime: FATAL EXCEPTION: Thread-4944
                                                                                 Process: com.getkeepsafe.relinker.sample, PID: 22887
                                                                                 com.getkeepsafe.relinker.MissingLibraryException: lib/armeabi/libdl.so
                                                                                     at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:85)
                                                                                     at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:182)
                                                                                     at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:140)
                                                                                     at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:96)
                                                                                     at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:191)
                                                                                     at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:140)
                                                                                     at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:96)
                                                                                     at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:191)
                                                                                     at com.getkeepsafe.relinker.ReLinkerInstance.access$000(ReLinkerInstance.java:35)
                                                                                     at com.getkeepsafe.relinker.ReLinkerInstance$1.run(ReLinkerInstance.java:146)
                                                                                     at java.lang.Thread.run(Thread.java:818)```

**Comment by BlueBirdZhangHua** [comment]
Here is the log before crash. Thanks again!
`04-29 16:49:20.994 21150-21210/com.getkeepsafe.relinker.sample D/ReLinker: hello (null) was not loaded normally, re-linking...
04-29 16:49:20.995 21150-21210/com.getkeepsafe.relinker.sample D/ReLinker: Forcing a re-link of hello (null)...
04-29 16:49:20.995 21150-21210/com.getkeepsafe.relinker.sample D/ReLinker: Looking for lib/armeabi/libhello.so in APK...
04-29 16:49:20.995 21150-21210/com.getkeepsafe.relinker.sample D/ReLinker: Found lib/armeabi/libhello.so! Extracting...
04-29 16:49:21.008 21150-21210/com.getkeepsafe.relinker.sample D/ReLinker: Beginning load of stdc++...
04-29 16:49:21.009 21150-21210/com.getkeepsafe.relinker.sample D/ReLinker: stdc++ (null) was loaded normally!
04-29 16:49:21.009 21150-21210/com.getkeepsafe.relinker.sample D/ReLinker: Beginning load of m...
04-29 16:49:21.010 21150-21210/com.getkeepsafe.relinker.sample D/ReLinker: m (null) was loaded normally!
04-29 16:49:21.010 21150-21210/com.getkeepsafe.relinker.sample D/ReLinker: Beginning load of c...
04-29 16:49:21.010 21150-21210/com.getkeepsafe.relinker.sample D/ReLinker: c (null) was loaded normally!
04-29 16:49:21.010 21150-21210/com.getkeepsafe.relinker.sample D/ReLinker: Beginning load of dl...
04-29 16:49:21.012 21150-21210/com.getkeepsafe.relinker.sample D/ReLinker: Loading the library normally failed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__cxa_finalize" referenced by "/system/lib/libdl.so"...
                                                                               at java.lang.Runtime.loadLibrary(Runtime.java:372)`

**Comment by BlueBirdZhangHua** [comment]
I work nicely after i modify some code  in ReLinkerInstance.java
`        try {
            if (recursive) {
                final ElfParser parser = new ElfParser(workaroundFile);
                final List<String> dependencies = parser.parseNeededDependencies();
                for (final String dependency : dependencies) {
                    try {
                        loadLibrary(context, libraryLoader.unmapLibraryName(dependency));
                    }catch (Exception e){
                        e.printStackTrace();
                    }
                }
            }`

**Comment by BlueBirdZhangHua** [comment]
Why we need to find needed dependencied?  In my opinion we just load the libhello.so and libhellojni.so will be fine? Can you help me?

**Comment by BlueBirdZhangHua** [comment]
`Sorry for offering a terrible solution before. After read some codes. I find out that remove                  recursively() will be fine. But still i don't know why we need to recursively() can you tell me?

**Comment by BlueBirdZhangHua** [comment]
After remove recursively() to disable searching dependencies for SO file. It got error at System.load() function. It make me confused. Why is ok for System.loadLibrary to only load hello.so. But for System.load() we need to load hello.so's dependencies first?

**Comment by xiphirx** [comment]
Hi,

Can you share what version of Android you're using? Not being able to load `libdl.so` sounds like a pretty large issue as it's pretty much guaranteed to exist / work...

As for your question: ReLinker will only parse the needed dependencies inside of your supplied .so file if you specify the `recursively()` modifier to your call. The reason this exists is explained [here](https://medium.com/keepsafe-engineering/relinker-v1-2-is-here-b8f1799e22fe) under "Recursive Loading." The basic gist of it is that under API 18 Android will not correctly resolve intra-library dependencies for you, forcing you to load them yourself explicitly. If you are not targeting < 18 then you do not need to specify `recursively`. The sample uses this just to show it off.

Either way, loading `libdl.so`, especially from `/system/lib/` should really never fail.

**Comment by xiphirx** [comment]
@BlueBirdZhangHua Do you still need assistance? If not, I will close this issue in a day or so

**Comment by BlueBirdZhangHua** [comment]
@xiphirx Sorry for reply so late. Beacuse I had a holiday. Relinker  works work very well,after I remove `recursively()`.Thanks for your  contribution. And the error `com.getkeepsafe.relinker.MissingLibraryException:lib/armeabi/libdl.so ` was still there bu not bother me any more.  As you asked i was using a phone with Android 6.0.1.

**Comment by xiphirx** [comment]
What device model? It's very weird that the phone cannot load `libdl.so`

**Comment by BlueBirdZhangHua** [comment]
MI3 . Maybe it's just a system problem. Because when Android 6.0 release came out on MI3,there is quite a lot of problems at first. Thanks anyway~   I think you can close this issue now.

**Comment by TheChuckster** [comment]
Hi @xiphirx and @BlueBirdZhangHua, I did encounter this issue as well (with my own native activity's .so), and the solution/workaround for me was to explicitly load all of its .so dependencies first.
