### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Cannot load library: find_library[]:  '*.so' failed to load previously

### ISSUE THREAD

**Issue by jonameson** [KeepSafe/ReLinker#20]
Hey guys great work with this library. It has resolved various crashes on our app. 

We are currently getting the following issue reported by the GooglePlay dev console. Hope you guys have an idea on how to resolve it or how we can resolve it.

We have 3 shared libraries being loaded: 
**libffmpeg.so, libskia_android.so, and libfc.so**

Architecture supported: 
**armeabi, armeabi-v7a, x86, and arm64-v8a**

----
## Reported crash
_Android:_ 
**4.0.3 - 4.0.4**

_Devices:_
<img width="295" alt="screen shot 2016-06-13 at 9 52 29 am" src="https://cloud.githubusercontent.com/assets/292403/16009879/95dda48c-314c-11e6-810a-6c7b7938c0a4.png">

_Log:_
```logs
java.lang.UnsatisfiedLinkError: Cannot load library: find_library[1199]:    94 'libfc.so' failed to load previously
	at java.lang.Runtime.load(Runtime.java:340)
	at java.lang.System.load(System.java:521)
	at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:200)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:140)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
	at com.vblast.fclib.Config.init(Config.java:23)
	at com.vblast.flipaclip.App.onCreate(App.java:59)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:973)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3968)
	at android.app.ActivityThread.access$1300(ActivityThread.java:128)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4514)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
	at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by xiphirx** [comment]
Hi there! Glad to hear ReLinker is resolving issues for you!

In regards to your issue, please take a look at #15 for more information on what is causing the library to fail to load and what you can do to alleviate the issue. Let me know if that doesn't adequately answer your question.

In the case it doesn't: which of the libraries you listed are you packaging with your APK?

**Comment by xiphirx** [comment]
@jonameson any updates?

**Comment by jonameson** [comment]
Hey @xiphirx sorry for not replying any sooner. So the 3 listed libraries are being packaged with the app. All these errors started happening after we included the arm64-v8a build. Really odd...

I'll have to look deeper into #15 to see if it can help us.

**Comment by jonameson** [comment]
Ok @xiphirx I think my issue might be related to #15. Thanks for the help! I think you can close this.
