### ISSUE TITLE
Cannot call native function after "DELETE AND KILL"

### ISSUE THREAD

**Issue by patrickwtl** [KeepSafe/ReLinker#30]
I have a rooted Nexus 6P,  I cannot call native function after I clicked "DELETE AND KILL" button. I found that directory '/data/app/com.getkeepsafe.relinker.sample-1/lib' is empty. Is it the reason why relinker cannot copy so back to app?

```11-28 01:19:41.367 350-350/? I/art: Late-enabling -Xcheck:jni
11-28 01:19:41.402 350-350/com.getkeepsafe.relinker.sample W/System: ClassLoader referenced unknown path: /data/app/com.getkeepsafe.relinker.sample-1/lib/arm
11-28 01:19:41.455 350-374/com.getkeepsafe.relinker.sample D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
11-28 01:19:41.554 350-374/com.getkeepsafe.relinker.sample I/Adreno: QUALCOMM build                   : 63c06b2, I8366cd0437
                                                                     Build Date                       : 12/06/15
                                                                     OpenGL ES Shader Compiler Version: XE031.05.13.02
                                                                     Local Branch                     : mybranch17112971
                                                                     Remote Branch                    : quic/LA.BF64.1.2.9_v2
                                                                     Remote Branch                    : NONE
                                                                     Reconstruct Branch               : NOTHING
11-28 01:19:41.559 350-374/com.getkeepsafe.relinker.sample I/OpenGLRenderer: Initialized EGL, version 1.4
11-28 01:19:42.940 350-350/com.getkeepsafe.relinker.sample E/art: No implementation found for java.lang.String com.getkeepsafe.relinker.sample.Native.helloJni() (tried Java_com_getkeepsafe_relinker_sample_Native_helloJni and Java_com_getkeepsafe_relinker_sample_Native_helloJni__)
11-28 01:19:42.941 350-350/com.getkeepsafe.relinker.sample D/ReLinker: Beginning load of hellojni...
11-28 01:19:42.944 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Loading the library normally failed: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.getkeepsafe.relinker.sample-1/base.apk"],nativeLibraryDirectories=[/data/app/com.getkeepsafe.relinker.sample-1/lib/arm, /data/app/com.getkeepsafe.relinker.sample-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libhellojni.so"
                                                                           at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                           at java.lang.System.loadLibrary(System.java:1076)
                                                                           at com.getkeepsafe.relinker.SystemLibraryLoader.loadLibrary(SystemLibraryLoader.java:24)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:163)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.access$000(ReLinkerInstance.java:31)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance$1.run(ReLinkerInstance.java:142)
                                                                           at java.lang.Thread.run(Thread.java:818)
11-28 01:19:42.944 350-438/com.getkeepsafe.relinker.sample D/ReLinker: hellojni (1.0) was not loaded normally, re-linking...
11-28 01:19:42.945 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Forcing a re-link of hellojni (1.0)...
11-28 01:19:42.946 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Looking for lib/armeabi-v7a/libhellojni.so in APK...
11-28 01:19:42.946 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Found lib/armeabi-v7a/libhellojni.so! Extracting...
11-28 01:19:42.959 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Beginning load of hello...
11-28 01:19:42.960 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Loading the library normally failed: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.getkeepsafe.relinker.sample-1/base.apk"],nativeLibraryDirectories=[/data/app/com.getkeepsafe.relinker.sample-1/lib/arm, /data/app/com.getkeepsafe.relinker.sample-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libhello.so"
                                                                           at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                           at java.lang.System.loadLibrary(System.java:1076)
                                                                           at com.getkeepsafe.relinker.SystemLibraryLoader.loadLibrary(SystemLibraryLoader.java:24)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:163)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:189)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.access$000(ReLinkerInstance.java:31)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance$1.run(ReLinkerInstance.java:142)
                                                                           at java.lang.Thread.run(Thread.java:818)
11-28 01:19:42.960 350-438/com.getkeepsafe.relinker.sample D/ReLinker: hello (null) was not loaded normally, re-linking...
11-28 01:19:42.961 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Forcing a re-link of hello (null)...
11-28 01:19:42.961 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Looking for lib/armeabi-v7a/libhello.so in APK...
11-28 01:19:42.961 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Found lib/armeabi-v7a/libhello.so! Extracting...
11-28 01:19:42.970 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Beginning load of stdc++...
11-28 01:19:42.971 350-438/com.getkeepsafe.relinker.sample D/ReLinker: stdc++ (null) was loaded normally!
11-28 01:19:42.971 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Beginning load of m...
11-28 01:19:42.971 350-438/com.getkeepsafe.relinker.sample D/ReLinker: m (null) was loaded normally!
11-28 01:19:42.971 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Beginning load of c...
11-28 01:19:42.972 350-438/com.getkeepsafe.relinker.sample D/ReLinker: c (null) was loaded normally!
11-28 01:19:42.972 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Beginning load of dl...
11-28 01:19:42.973 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Loading the library normally failed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__cxa_finalize" referenced by "/system/lib/libdl.so"...
                                                                           at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                           at java.lang.System.loadLibrary(System.java:1076)
                                                                           at com.getkeepsafe.relinker.SystemLibraryLoader.loadLibrary(SystemLibraryLoader.java:24)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:163)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:189)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:189)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance.access$000(ReLinkerInstance.java:31)
                                                                           at com.getkeepsafe.relinker.ReLinkerInstance$1.run(ReLinkerInstance.java:142)
                                                                           at java.lang.Thread.run(Thread.java:818)
11-28 01:19:42.973 350-438/com.getkeepsafe.relinker.sample D/ReLinker: dl (null) was not loaded normally, re-linking...
11-28 01:19:42.974 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Forcing a re-link of dl (null)...
11-28 01:19:42.974 350-438/com.getkeepsafe.relinker.sample D/ReLinker: Looking for lib/armeabi/libdl.so in APK...```

**Comment by xiphirx** [comment]
It seems like your phone failed to load `libdl` which is very odd. Can you try specifying `recursively(false)` ?

**Comment by xiphirx** [comment]
Hi @patrickwtl any updates on this?

**Comment by xiphirx** [comment]
Closing due to inactivity
