### ISSUE TITLE
.so loads but not able to call native func

### ISSUE THREAD

**Issue by kkrishnan90** [KeepSafe/ReLinker#34]
Hey, 
Here's the stack trace of my log with Relinker. The .so file seems to load normally but fails to call any native method that's being implemented inside the .so file. 
Note : I am using your library listener with jnr-ffi for Android devices. 
**Stacktrace from Relinker**
```
04-21 11:50:59.032 4455-4455/com.example.expertonetechnologies.jnrsample E/Native Directory: /data/app/com.example.expertonetechnologies.jnrsample-2/lib/arm
04-21 11:50:59.032 4455-4455/com.example.expertonetechnologies.jnrsample E/Files: Size: 2
04-21 11:50:59.033 4455-4455/com.example.expertonetechnologies.jnrsample E/CPU ARCH TYPE: armeabi
04-21 11:50:59.037 4455-4455/com.example.expertonetechnologies.jnrsample E/Relink Logged: Beginning load of ffi_demo_old...
04-21 11:50:59.039 4455-4503/com.example.expertonetechnologies.jnrsample E/Relink Logged: ffi_demo_old (null) was loaded normally!
04-21 11:50:59.039 4455-4503/com.example.expertonetechnologies.jnrsample E/FFI DEMO: LIBRARY LOADED SUCCESSFULLY 

```

Just curious on what does that ```null``` mean in ```ffi_demo_old (null)```
Here's my Android Java Code. 

```
ReLinker.log(new ReLinker.Logger() {
                @Override
                public void log(String message) {
                    Log.e("Relink Logged",message);
                }
            }).loadLibrary(MainActivity.this, "ffi_demo_old", new ReLinker.LoadListener() {
                @Override
                public void success() {
                   //Calling jnr-ffi library to load the interface class thereby calling the native method
                    RustLib rustLib=LibraryLoader.create(RustLib.class).load("ffi_demo_old");
                    rustLib.double_input(10);
                    Log.e("FFI DEMO","LIBRARY LOADED SUCCESSFULLY");
                }

                @Override
                public void failure(Throwable t) {
                    Log.e("FFI DEMO","LIBRARY LOADED FAILED");
                    t.printStackTrace();
                }
            });
```

This one now throws me an error and here's the stacktrace of the same for your reference. Gives me an ambiguous output in the logger. 

```
04-21 11:55:08.489 7360-7360/com.example.expertonetechnologies.jnrsample E/Native Directory: /data/app/com.example.expertonetechnologies.jnrsample-1/lib/arm
04-21 11:55:08.489 7360-7360/com.example.expertonetechnologies.jnrsample E/Files: Size: 2
04-21 11:55:08.489 7360-7360/com.example.expertonetechnologies.jnrsample E/CPU ARCH TYPE: armeabi
04-21 11:55:08.493 7360-7360/com.example.expertonetechnologies.jnrsample E/Relink Logged: Beginning load of ffi_demo_old...
04-21 11:55:08.494 7360-7391/com.example.expertonetechnologies.jnrsample E/Relink Logged: ffi_demo_old (null) was loaded normally!
04-21 11:55:08.506 7360-7392/com.example.expertonetechnologies.jnrsample D/AppTracker: App Event: start
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample E/FFI DEMO: LIBRARY LOADED FAILED
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err: java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.provider.InvalidProvider$1.loadLibrary(InvalidProvider.java:30)
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.LibraryLoader.load(LibraryLoader.java:269)
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.LibraryLoader.load(LibraryLoader.java:248)
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.example.expertonetechnologies.jnrsample.MainActivity$1.success(MainActivity.java:50)
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.getkeepsafe.relinker.ReLinkerInstance$1.run(ReLinkerInstance.java:143)
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at java.lang.Thread.run(Thread.java:761)
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err: Caused by: java.lang.ExceptionInInitializerError
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:49)
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at java.lang.Class.newInstance(Native Method)
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.access$000(FFIProvider.java:56)
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.LibraryLoader.create(LibraryLoader.java:52)
04-21 11:55:08.521 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err: 	... 3 more
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err: Caused by: java.lang.IllegalStateException: Can't overwrite cause with java.lang.UnsatisfiedLinkError
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:252)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.Type.resolveSize(Type.java:155)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.Type.size(Type.java:138)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:178)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:57)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:53)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err: 	... 11 more
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err: Caused by: java.lang.UnsatisfiedLinkError
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.Foreign.newLoadError(Foreign.java:72)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.Foreign.access$300(Foreign.java:42)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.Foreign$InValidInstanceHolder.getForeign(Foreign.java:98)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err: 	... 19 more
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err: Caused by: java.lang.UnsatisfiedLinkError
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.Init.newLoadError(Init.java:132)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.Init.load(Init.java:89)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
04-21 11:55:08.522 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err: 	... 21 more
04-21 11:55:08.523 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err: Caused by: java.lang.RuntimeException: cannot determine CPU
04-21 11:55:08.523 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.internal.StubLoader.determineCPU(StubLoader.java:189)
04-21 11:55:08.523 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.internal.StubLoader.getCPU(StubLoader.java:193)
04-21 11:55:08.523 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.internal.StubLoader.getPlatformName(StubLoader.java:221)
04-21 11:55:08.523 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.internal.StubLoader.loadFromBootPath(StubLoader.java:306)
04-21 11:55:08.523 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:246)
04-21 11:55:08.523 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:431)
04-21 11:55:08.523 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at java.lang.Class.classForName(Native Method)
04-21 11:55:08.523 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at java.lang.Class.forName(Class.java:400)
04-21 11:55:08.523 7360-7391/com.example.expertonetechnologies.jnrsample W/System.err:     at com.kenai.jffi.Init.load(Init.java:68)
```

Sorry for such a long post . Thanks for your patience in taking time to read this one 😄 
Awaiting your response over this issue.

**Comment by benjamin-bader** [comment]
This is the actual exception that started the load failure:
```
Caused by: java.lang.RuntimeException: cannot determine CPU
    at com.kenai.jffi.internal.StubLoader.determineCPU(StubLoader.java:189)
    at com.kenai.jffi.internal.StubLoader.getCPU(StubLoader.java:193)
    at com.kenai.jffi.internal.StubLoader.getPlatformName(StubLoader.java:221)
    at com.kenai.jffi.internal.StubLoader.loadFromBootPath(StubLoader.java:306)
    at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:246)
    at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:431)
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:400)
    at com.kenai.jffi.Init.load(Init.java:68)
```

Looks like something is failing in your code.

**Comment by kkrishnan90** [comment]
Then how could the log before that show the CPU abi ?? A bit confused :confused:

**Comment by kkrishnan90** [comment]
It shows cpu is armeabi ..

**Comment by benjamin-bader** [comment]
The log format is "$libname ($version)", basically.  `null` is for the library version, which your code doesn't appear to specify - therefore it is null, and that's what gets logged.

Now that I look more closely, I see that ReLinker is succeeding.  The crash is happening in your `success` callback, when you're invoking some other library to load what appears to be a Rust binary.  We can't do anything more to help you; you'll have to fix your code yourself.

I suggest investigating your dependencies more closely; whatever this `StubLoader` thing is, it is failing at class-load time, i.e. in its static initializer.

**Comment by xiphirx** [comment]
ReLinker is doing its job properly here, which is loading your library. The issue you're running into is due to JNR-FFI. JNR-FFI does not seem to support Android well, if at all. 

If you're trying to make JNR work on Android, you actually shouldn't use ReLinker, but rather the library loading capabilities of JNR itself since it needs to generate the library interface implementation necessary to operate.

You would likely find more help at the [appropriate repository](https://github.com/jnr/jnr-ffi)

**Comment by ranjankumar03** [comment]
any idea of this issue?


2017-09-01 04:41:59,317 DEBUG APP=697 COMP=623 [main] datastax.driver.core.Native:113 -Could not load JNR C Library, native system calls through this library will
not be available
java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
        at jnr.ffi.provider.InvalidProvider$1.loadLibrary(InvalidProvider.java:48)
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:290)
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:269)
        at com.datastax.driver.core.Native$LibCLoader.<clinit>(Native.java:108)
        at com.datastax.driver.core.Native.isGettimeofdayAvailable(Native.java:190)
        at com.datastax.driver.core.ClockFactory.newInstance(Clock.java:51)
        at com.datastax.driver.core.AbstractMonotonicTimestampGenerator.<init>(AbstractMonotonicTimestampGenerator.java:43)
        at com.datastax.driver.core.LoggingMonotonicTimestampGenerator.<init>(LoggingMonotonicTimestampGenerator.java:49)
        at com.datastax.driver.core.AtomicMonotonicTimestampGenerator.<init>(AtomicMonotonicTimestampGenerator.java:50)
        at com.datastax.driver.core.AtomicMonotonicTimestampGenerator.<init>(AtomicMonotonicTimestampGenerator.java:37)
        at com.datastax.driver.core.policies.Policies.defaultTimestampGenerator(Policies.java:121)
        at com.datastax.driver.core.policies.Policies$Builder.build(Policies.java:286)
        at com.datastax.driver.core.Cluster$Builder.getConfiguration(Cluster.java:1317)
        at com.datastax.driver.core.Cluster.<init>(Cluster.java:113)
        at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:178)

**Comment by benjamin-bader** [comment]
@ranjankumar03 
1. your error appears to be unrelated to this issue; please open a _new_ issue instead of commenting on someone else's.
2. More importantly, nothing in the stacktrace you posted suggests that ReLinker is involved.  Please check with the vendor whose library you are using.

**Comment by Andreby42** [comment]
-Dcom.datastax.driver.USE_NATIVE_CLOCK=false  

try use this vm arg
