### ISSUE TITLE
Caused by: com.getkeepsafe.relinker.MissingLibraryException: libmmkv.so

### ISSUE THREAD

**Issue by wlj190785060** [KeepSafe/ReLinker#78]
java.lang.RuntimeException: Unable to create application com.vivo.health.app.VivoHealthApplication: com.getkeepsafe.relinker.MissingLibraryException: libmmkv.so
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7195)
	at android.app.ActivityThread.access$1500(ActivityThread.java:265)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2152)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:8179)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
Caused by: com.getkeepsafe.relinker.MissingLibraryException: libmmkv.so
	at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:24)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:15)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:6)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:4)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:1)

**Comment by thelou1s** [comment]
Same problem:

<img width="974" alt="image" src="https://user-images.githubusercontent.com/5654770/177246784-ea209e91-3283-47d8-86bd-51b0ccd8beb6.png">

log:
```
Non-fatal Exception: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libmmkv.so'. Looked for: [armeabi-v7a, armeabi], but only found: [].
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java)
       at util.MmkvUtils.lambda$initialize$0(MmkvUtils.java)
       at util.-$$Lambda$MmkvUtils$sbLe1HJ9hfpxq8bb2XEO8Byn1ew.loadLibrary(-.java)
       at com.tencent.mmkv.MMKV.doInitialize(MMKV.java)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java)
       at util.MmkvUtils.initialize(MmkvUtils.java)
```


java:
```
public class MmkvUtils {

    private static final String TAG = "MmkvUtils";

    private static volatile MMKV sMultiProcessMmkv;
    //private static volatile MMKV sDefaultMmkv;

    private MmkvUtils() {
    }

    public static void initialize(Context context) {
        String pathDir = context.getFilesDir().getAbsolutePath() + "/mmkv";
        String rootDir = MMKV.initialize(pathDir, libName -> {
            ReLinker.loadLibrary(context, libName);
        });
        Log.d(TAG, "initialize: " + rootDir);
    }

    public static MMKV multiProcessMmkv() {
        if (sMultiProcessMmkv == null) {
            synchronized (MmkvUtils.class) {
                if (sMultiProcessMmkv == null) {
                    ensureInitialized();
                    sMultiProcessMmkv = MMKV.mmkvWithID("MultiProcessMmkv", MMKV.MULTI_PROCESS_MODE);
                }
            }
        }
        return sMultiProcessMmkv;
    }

    private static void ensureInitialized() {
        if (TextUtils.isEmpty(MMKV.getRootDir())) {
            MMKV.initialize(AppUtils.getApp());
        }
    }
```

**Comment by CharlieZheng** [comment]
Is there any one maintain this project. Facing the same crash.

**Comment by evgenybozhko2** [comment]
Similar issue. Bump up
