### ISSUE TITLE
Unable to find the library even though it is existing in the Apk of the devices which is causing the issue

### ISSUE THREAD

**Issue by Zaraki596** [KeepSafe/ReLinker#98]
`Caused by com.getkeepsafe.relinker.b: Could not find 'libjni_latinime.so'. Looked for: [armeabi-v7a, armeabi], but only found: [].
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:175)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
       at com.android.inputmethod.latin.utils.JniUtils.<clinit>(JniUtils.java:30)
       at com.android.inputmethod.latin.utils.JniUtils.loadNativeLibrary(JniUtils.java)
       at com.android.inputmethod.latin.BinaryDictionary.<clinit>(BinaryDictionary.java:228)
       at com.android.inputmethod.indic.ExpandableBinaryDictionary.openBinaryDictionaryLocked(ExpandableBinaryDictionary.java:272)
       at com.android.inputmethod.indic.ExpandableBinaryDictionary.loadBinaryDictionaryLocked(ExpandableBinaryDictionary.java:626)
       at com.android.inputmethod.indic.ExpandableBinaryDictionary.access$700(ExpandableBinaryDictionary.java:56)
       at com.android.inputmethod.indic.ExpandableBinaryDictionary$12.run(ExpandableBinaryDictionary.java:689)
       at com.android.inputmethod.indic.ExpandableBinaryDictionary$1.run(ExpandableBinaryDictionary.java:212)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)`

<img width="1026" alt="Screenshot 2022-05-06 at 11 11 09 AM" src="https://user-images.githubusercontent.com/23017590/167073744-66bc8e13-97bc-4b11-8bf5-b17b337161ad.png">

As you can see in the image in the file it is existing in the Apk, this is one of the prominent devices apk in which crashes are coming.
Any specific reason why is coming?

**Comment by umberto-sonnino** [comment]
We've recently seen this reported as well on a number of devices and Android versions. Android 10, 11 and 12 account for ~60% of the reports, but it's happening on other versions too.

**Comment by iamskullking** [comment]
We also encountered this problem:

com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libmmkv.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary (ApkLibraryInstaller.java:173)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal (ReLinkerInstance.java:180)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:136)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:70)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:51)

This problem occurs with different android versions and different phone brands, mostly on android 10, 11 and 12, btw we used google aab function.

**Comment by gugasv** [comment]
We are facing this same problem. Are there any updates on this? Or any proposed workarounds?

**Comment by TomasRiker** [comment]
My impression is that it occurs after installing an app update. Can anyone confirm this?
